### ISSUE TITLE
Professor data

### ISSUE THREAD

**Issue by JakovTomasic** [JakovTomasic/RitehMaps#21]
Get a list of all professors, their names, and offices (link them to room data #19).

Save all the data into some formatted file, like JSON.

The data can be found [here](http://www.riteh.uniri.hr/kontakti/). It would be preferable if our data can change the moment the faculty changes its data (for example, by accessing it in real-time from their API). Otherwise, collect it using a web scrapper.

**Comment by JakovTomasic** [comment]
For a first step. Write a python script that generates wanted JSON file.

**Comment by NikaRodin** [comment]
The data was successfully collected using a web scraper, but due to Cross-Origin Read Blocking it cannot be used by the app or displayed in the browser real-time. A temporary solution was to manually hardcode the retrieved data into an object so that the rest of the app can use it.  We should find a way to fix this problem in the future. I'm opening a new issue for it - #46.
